
const Food=[
    {
        id:1,
        url:require("../component/Dashboard/image/Indfood-1.jpg"),
        rate:'50',
        title:'Idly',
        quantity:'2 pieces',
        star:4.5,
        description:'Idli are a type of savoury rice cake, originating from the Indian subcontinent, popular as breakfast foods in Southern India and in Sri Lanka. The cakes are made by steaming a batter consisting of fermented white gram whole and rice rava. and dipped into sambar. its also called as dip sambar idli.',
        titlename:'IndianFood',
        titleId:1
    },
    {
        id:2,
        url:require("../component/Dashboard/image/Indfood-2.jpg"),
        rate:'100',
        title:'Dosa',
        quantity:'2 pieces',
        star:4.5,
        description:'A thin and crispy pancake prepared with fermented dosa batter which is topped with red garlic chutney and potato masala. the appearance and texture is very similar to world famous masala dosa. but the main difference lies with the red garlic chutney spread topped on bangalore dosa.',
        fakerate:900,
        titlename:'IndianFood',
        titleId:1
    },
    {
        id:3,
        url:require("../component/Dashboard/image/Indfood-3.jpg"),
        rate:'100',
        title:'Puri',
        quantity:'2 pieces',
        star:4.5,
        description:'South Indian style potato masala made with boiled, crumbled potatoes in mild, flavorful gravy. It is served with hot Poori which is a deep-fried bread made from unleavened whole-wheat flour',
        titlename:'IndianFood',
        titleId:1
    },
    {
        id:4,
        url:require("../component/Dashboard/image/Indfood-4.jpg"),
        rate:'100',
        title:'Upma',
        quantity:'1 Serve',
        star:3,
        description:"The best aromatic upma topped with vegetables and ghee and it comes with more vegetables. Staying consious of one's health is the way to go, thus is a light upma made of wheat grains and vegetable ",
        titlename:'IndianFood',
        titleId:1
    },
    {
        id:5,
        url:require("../component/Dashboard/image/Indfood-5.jpg"),
        rate:'100',
        title:'Puri Bhaji',
        quantity:'2 pieces',
        star:5,
        description:'Puri Bhaji is a classic Indian dish consisting of deep-fried, golden puffed puris served with a deliciously spiced potato curry. This comforting combination is loved across India for its rich flavor, crisp texture, and satisfying taste. Perfect for breakfast, lunch, or festive meals.',
        titlename:'IndianFood',
        titleId:1
    },
    {
        id:6,
        url:require("../component/Dashboard/image/Indfood-6.jpg"),
        rate:'100',
        title:'Biriyani',
        quantity:'1 Serve',
        star:4,
        description:'Rich in taste and creamy in texture. Think we are talking about a dessert? Well,this biryani might as well be one with the way it melts in your mouth. Tender chicken is marinated in yogurt&spices to make this biryani delicious',
        titlename:'IndianFood',
        titleId:1
    },
    {
        id:7,
        url:require("../component/Dashboard/image/Indfood-7.jpg"),
        rate:'100',
        title:'Chapati bhaji',
        quantity:'2 pieces',
        star:5,
        description:'Chapati Bhaji is a simple and healthy Indian meal. Chapati is a soft flatbread made from wheat flour, and bhaji is a cooked vegetable dish with spices. The vegetables are boiled or fried with onions, tomatoes, and basic masalas. This meal is easy to make, light to eat, and commonly enjoyed for breakfast, lunch, or dinner.',
        title:'Chapati Bhaji',
        titleId:1,
        titlename:'IndianFood',
        titleId:1
    },
    {
        id:8,
        url:require("../component/Dashboard/image/Indfood-8.jpg"),
        rate:'100',
        title:'Paneer Bhaji, Butter Roti, and Jeera Mutter Rice',
        quantity:'2 pieces',
        star:4.5,
        description:'Paneer Bhaji, Butter Roti, and Jeera Mutter Rice make a delicious Indian meal. Paneer bhaji is a spicy and tasty curry made with soft paneer cubes cooked in onions, tomatoes, and Indian spices. Butter roti is a soft wheat flatbread brushed with butter, which adds a rich flavor. Jeera mutter rice is a fragrant rice dish made with cumin seeds (jeera), green peas (mutter), and cooked in ghee or oil. This combination is full of flavor, satisfying, and loved by all age groups.',
        titlename:'IndianFood',
        titleId:1
    },
    {
        id:9,
        url:require("../component/Dashboard/image/Indfood-9.jpg"),
        rate:'100',
        title:'Kaju Masala Roti',
        quantity:'6 pieces',
        star:5,
        description:'Kaju Masala is a rich and creamy curry made with cashew nuts cooked in a spicy tomato and onion gravy. It has a slightly sweet and buttery taste, often flavored with Indian spices and cream. It is served hot with roti, a soft wheat flatbread. This combination is tasty and often enjoyed in restaurants or special meals.',
        titlename:'IndianFood',
        titleId:1
    },
    {
        id:10,
        url:require("../component/Dashboard/image/Indfood-10.jpg"),
        rate:'100',
        title:'Pav baaji',
        quantity:'2 pieces',
        star:5,
        description:'Pav Bhaji is a fast food dish from Mumbai (Bombay), India, consisting of a vegetable curry (bhaji) cooked in tomato gravy and served with a soft bread roll (pav).',
        titlename:'IndianFood',
        titleId:1
    },
    {
        id:11,
        url:require("../component/Dashboard/image/Indfood-11.png"),
        rate:'100',
        title:'Parotta',
        quantity:'3 pieces',
        star:5,
        description:'Parotta or Porotta is a layered Indian and Sri Lankan flatbread made from Maida or Atta, alternatively known as flaky ribbon pancake.',
        titlename:'IndianFood',
        titleId:1
    },
    {
        id:12,
        url:require("../component/Dashboard/image/indfood-12.png"),
        rate:'100',
        title:'Veg meals',
        quantity:'1 Serve',
        star:5,
        description:'A vegetarian diet does not include any meat, poultry, or seafood. It is a meal plan made up of foods that come mostly from plants',
        titlename:'IndianFood',
        titleId:1
    },
        {
            id:2.1,
            url:require("../component/Dashboard/image/Italifood-1.jpg"),
            rate:'300',
            title:'Spaghetti',
            quantity:'2 pieces',
            star:4.5,
            titlename:'JunkFood',
            titleId:2,
            description:'Spaghetti is a long, thin, solid, cylindrical noodle pasta. Like other pasta, spaghetti is made of milled wheat and water and sometimes enriched with vitamins and minerals. Italian dried spaghetti is made from durum wheat semolina, however; outside of Italy, it can be made in a variety of different ways.'
        },
        {
            id:2.2,
            url:require("../component/Dashboard/image/italifood-2.jpg"),
            rate:'30',
            title:'Vadapav',
            quantity:'2 pieces',
            star:4.5,
            titlename:'JunkFood',
            titleId:2,
            description:'Vada Pav is a famous Indian street food from Maharashtra. It consists of a spicy potato fritter (vada) placed inside a soft bun (pav) along with chutneys and fried green chili. It is tasty, spicy, and perfect for a quick snack.'},
        {id:2.3,
            url:require("../component/Dashboard/image/italifood-3.jpg"),
            rate:'200',
            title:' Combo MN',
            quantity:'1 serve',
            star:5,
            titlename:'JunkFood',
            titleId:2,
            description:'Manchurian and Noodles Combo is a popular Indo-Chinese meal. Noodles are stir-fried with vegetables, sauces, and spices to give a tasty flavor. Manchurian balls made from vegetables or paneer are cooked in a spicy and tangy gravy. Together, this combo is delicious, spicy, and loved by kids and adults alike.'},
        {id:2.4,
            url:require("../component/Dashboard/image/italifood-4.jpg"),
                rate:'120',
                title:'Burger',
                quantity:'2 serve',
                star:4.5,
                titlename:'JunkFood',
                titleId:2,
                description:'A burger is a popular fast food made with a soft bun filled with a patty (vegetable or meat), lettuce, tomato, onion, cheese, and sauces. It is tasty, easy to eat, and loved by people of all ages. It can be served with fries or cold drinks for a complete meal.'},
        {id:2.5,
            url:require("../component/Dashboard/image/italifood-5.jpg"),
                rate:'200',
                title:'Veg Mix Pizza',
                quantity:'1 serve',
                star:4.5,
                titlename:'JunkFood',
                titleId:2,
                description:'Veg Mix Pizza is a delicious Italian dish topped with a variety of vegetables like capsicum, onions, tomatoes, sweet corn, and olives. It has a soft or crispy base, tasty tomato sauce, melted cheese, and mixed spices. This colorful and cheesy pizza is perfect for veg lovers and is enjoyed as a snack or meal.'},
        {id:2.6,
            url:require("../component/Dashboard/image/italifood-6.jpg"),
                rate:'100',
                title:'Manchow Soup',
                quantity:'2 serve',
                star:4.5,
                titlename:'JunkFood',
                titleId:2,
            description:'Manchow Soup is a hot and spicy Indo-Chinese soup made with chopped vegetables, garlic, ginger, and soy sauce. It is thick, flavorful, and usually topped with crispy fried noodles. This soup is a favorite starter and perfect for cold weather.'},
            {id:2.7,
                url:require("../component/Dashboard/image/Italifood-7.png"),
                rate:'200',
                title:'Foccacia',
                quantity:'1 piece',
                star:4.5,
                titlename:'JunkFood',
                titleId:2,
            description:'Focaccia is made from flour, oil, water, yeast, and salt, like pizza dough. However, it has more yeast than pizza dough, which allows it to rise more and make a fluffier, bread-like loaf. People love focaccia because of its smooth texture and taste.'},
            {
                id:2.8,
                url:require("../component/Dashboard/image/italifood-8.jpg"),
                rate:'150',
                title:'Pizza',
                quantity:'1 serve',
                star:4.5,
                titlename:'JunkFood',
                titleId:2,
            description:"With real italian pizza, you will find homemade sauce made from freshly peeled tomatoes and a blend of savory, complimenting herbs. You will also notice that authentic Italian pizza doesn't combine the toppings and sauce to be cooked together. They simply layer the sauce along the crus"},


    {
        id:3.1,
        url:require("../component/Dashboard/image/kor-1.jpg"),
        rate:'80',
        title:'Voli Bhel',
        quantity:'1 Serve',
        star:4.5,
        description:"Voli Bhel is a crunchy and spicy Indian street food made with puffed rice, sev, onions, tomatoes, and special chutneys.",
        fakerate:900,
        titlename:'chat',
        titleId:3
    },
    {
        id:3.2,
        url:require("../component/Dashboard/image/kor-2.jpg"),
        rate:'60',
        title:'Sukhi Bhel',
        quantity:'1 Serve',
        star:4.5,
        description:"Sukhi Bhel is a dry version of bhel made with puffed rice, onions, tomatoes, sev, and dry spices. It is light and crispy.",
        titlename:'chat',
        titleId:3
    },
    {
        id:3.3,
        url:require("../component/Dashboard/image/kor-3.jpg"),
        rate:'100',
        title:'Gheeli Ragada Bhel',
        quantity:'1 Serve',
        star:4.5,
        description:"Gheeli Ragada Bhel is made with spicy ragada (white peas), chutneys, puffed rice, and onions. It is a tangy and filling snack.",
        titlename:'chat',
        titleId:3
    },
    {
        id:3.4,
        url:require("../component/Dashboard/image/kor-4.jpg"),
        rate:'90',
        title:'Shev Papdi Bhel',
        quantity:'1 Serve',
        star:4.5,
        description:"Shev Papdi Bhel is a chatpata snack made with crispy papdi, shev, chutneys, onions, and curd. It has a mix of sweet and spicy taste.",
        titlename:'chat',
        titleId:3
    },
    {
        id:3.5,
        url:require("../component/Dashboard/image/kor-5.jpg"),
        rate:'50',
        title:'Panipuri',
        quantity:'6 pieces',
        star:4.5,
        description:"Panipuri is a popular street food with crispy puris filled with spicy water, potatoes, and chutneys. It is fun and refreshing.",
        titlename:'chat',
        titleId:3
    },
    {
        id:3.6,
        url:require("../component/Dashboard/image/kor-6.png"),
        rate:'70',
        title:'Ragda Puri',
        quantity:'6 pieces',
        star:4.5,
        description:"Ragda Puri is a puri-based chaat filled with hot white peas curry, chutneys, and sev. It is spicy, tangy, and flavorful.",
        titlename:'chat',
        titleId:3
    },
    {
        id:3.7,
        url:require("../component/Dashboard/image/kor-7.jpg"),
        rate:'80',
        title:'Dahi Puri',
        quantity:'6 pieces',
        star:4.5,
        description:"Dahi Puri is made with puris filled with curd, sweet chutney, spicy chutney, potatoes, and sev. It is cool and tasty.",
        titlename:'chat',
        titleId:3
    }
]

            
                
export default Food